### PR TITLE
optimize: replace lodash to lodash-es reduce package size

### PR DESCRIPTION
**Pull request by l1shen**
##### Checklist

- [ ] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change

- use lodash-es reduce package size

### CODE REVIEW

**Comment by kuitos** [comment]
thx for your nice contribution!
But we prefer do these with the compiler tool rather than manual replacement, and we plan to migrate the build system to [father-build](https://github.com/umijs/father#extrababelplugins), which could do the replacement automatically.

**Comment by PHenryy** [comment]
最新版本打包出的 lodash 的 parsed size 还是 24K，应该是个 full build，所以用了上面说的 `father-build` 还是没有 `tree shaking`, 请问是我配置的原因吗？

**Comment by kuitos** [comment]
这个 lodash 应该是你们项目自己引入并且没做 tree shaking 导致的，qiankun 的包 build 之后就已经做好模块化 import 处理了 https://unpkg.com/browse/qiankun@2.4.0/es/loader.js
image

**Comment by PHenryy** [comment]
@kuitos https://github.com/PHenryy/qiankun-template/tree/main/main-app 我把代码放到这个仓库里了，可以看一下吗，主项目没有用到 `lodash`, `npm run build` 开启了 `webpack` 分析，可以看到 `lodash` 的大小是 24k

**Comment by PHenryy** [comment]
应该是我搞错了，24kb是gzipped的全量大小，我build的24kb是parsed的大小，两个值接近导致混淆了

**Pull request closed without merging**
