### PR TITLE
fix(qiankun): should remove internal cache of loadMicroApp while loading failed

### LINKED ISSUE #1885: loadMicroApp 加载失败后，再一次执行，并不会重新发起http请求，而是直接报错
## What happens?

loadMicroApp 加载失败后，再一次执行，并不会重新发起http请求，而是直接报错

## Mini Showcase Repository(REQUIRED)
暂无

## How To Reproduce

将微应用服务停止 ，使用loadMicroApp 加载微应用，可以得到失败，然后将微应用重启，再次使用loadMicroApp 加载，此时不会发起新的请求，而是报错

## Context

- **qiankun Version**: 2.6.3
- **Platform Version**:window10
- **Browser Version**:Google Chrome 版本 96.0.4664.110（正式版本） (x86_64)

### LINKED ISSUE #1990: 网络或其他原因导致子应用加载失败，无法手动重新加载
## What happens?
使用loadMicroApp加载子应用，无法手动重新加载
------------------------------------------------------------------
Failed to load the subapplication using loadMicroApp and cannot be manually reloaded

## 复现步骤，错误日志以及相关配置
1. 关闭网络
2. 调用loadMicroApp加载子应用
3 加载失败后，没有可供重试的API
4. 此时卸载掉旧的实例再重新调用loadMicroApp， 并不会真的发出请求，而是把刚才加载的错误重新抛出了
------------------------------------------------------------------
1. Shut down the network
2. Call loadMicroApp to load subapplications
3 No API is available for retry after the loading fails
4. Uninstalling the old instance and calling loadMicroApp again does not actually issue the request. Instead, it rethrows the error that was just loaded

## 相关环境信息

- **qiankun 版本** 2.6.3
- **浏览器版本**： 98.0.4758.109
- **操作系统**：mac 12.1

### LINKED ISSUE #2166: [Feature Request] 能否提供彻底卸载loadMicroApp加载的子应用，下次进入能重新走首次流程
## Background

生产可能已经发布了新的子应用，但是用户由于已加载过子应用，导致无法获取到更新后的子应用
且子应用在部分js应网络问题加载失败后，无法通过再次加载子应用来提供访问重试的方案
## Proposal

建议提供彻底卸载方法来移除已加载过的子应用，能让子应用像首次加载子应用一样的流程

### LINKED ISSUE #2368: 【bug】关于loadMicroApp + 多实例 + 动态增减 tabs  导致的 appContainerXPathKey 计算结果存在重复
## 出现的问题?

loadMicroApp + 多实例 +tabs动态增减 会导致**appContainerXPathKey** 重复，导致挂载失败

## 复现仓库地址

https://github.com/laizq2020/qiankun-demo

## 如何复现

1. 主应用先连续新增3个及以上标签页
2. 关闭第一个或者第二个页签
3. 再次新增页签，子应用无法加载

### LINKED ISSUE #2854: [Bug]资源加载出错然后换一个entry, 但是name不变的话, 不会再次请求新资源
## What happens?

我们希望通过`loadMicroApp`加载资源A时, 假如资源加载失败, 比如: cdn问题或者cos问题, 会回退到另一个备份地址,然后重新加载插件. 阅读源码发现在通过`loadMicroApp`加载时, 会把`name`+`containerXPath`作为key缓存下来.  https://github.com/umijs/qiankun/blob/master/src/apis.ts#L148. 所以如果我只改`entry`, 是不会重新加载, 还必须把`name`也改了才行.

所以这里是不是要做下`catch`处理? 如果异常了,则把缓存也销毁了
或者直接用`name` +`entry` 作为缓存的`key`

## 复现步骤，错误日志以及相关配置

- 加载一个404的资源, 失败后
- 修改entry重新加载

## 相关环境信息

- **qiankun 版本** 2.10.16
- **浏览器版本**：
- **操作系统**：

### PR DESCRIPTION
**Pull request by kuitos**
* resolves #1885
* resolves #2166
* resolves #1990
* resolves #2854

### CODE REVIEW

**Review by bravepg — APPROVED** [review]
nice～

**Comment by HaishengLiang** [comment]
wait for new version release

**Comment by HaishengLiang** [comment]
+1

**Comment by zackBRAVE** [comment]
什么时候发布呢

**Comment by wudith** [comment]
基于路由加载子应用失败也有类似的问题，是否可以顺便一起处理下呢

**Pull request merged**
