### PR TITLE
Update loader.ts

### PR DESCRIPTION
**Pull request by wf-erikslokharts**
Non breaking change, added className to main 'div' in order to be able to target its css properties.

##### Checklist

- [X] `npm test` passes
- [N/A] tests are included
- [N/A] documentation is changed or added
- [404] commit message follows commit guidelines

##### Description of change

- any feature?
- close https://github.com/umijs/qiankun/ISSUE_URL

### CODE REVIEW

**Comment by kuitos** [comment]
`containerElement.className` is useless as `containerElement` will never be appended to document.

**Comment by wf-erikslokharts** [comment]
> `containerElement.className` is useless as `containerElement` will never be appended to document.

Ok if that's the case then where do we get extra div from, any idea?
`<div id="root-master">
   <div>
    <div id="__qiankun_microapp_...
`

**Comment by gongshun** [comment]
Can be like this `#container > div` ，https://developer.mozilla.org/en-US/docs/Web/CSS/Child_combinator

**Comment by wf-erikslokharts** [comment]
> Can be like this `#container > div` ，https://developer.mozilla.org/en-US/docs/Web/CSS/Child_combinator

Hey, thank you for suggestion this is how we did originally, but then thought it be nice if parental div would have a class similar to what '__qiankun_wrapper...' has, thats how this commit was created :D

**Comment by kuitos** [comment]
You can set the className of MicroApp wrapper while you are using @umijs/plugin-qiankun 
image

see https://umijs.org/plugins/plugin-qiankun#loading-%E5%8A%A8%E7%94%BB%E4%B8%8E%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F

**Pull request closed without merging**
