### PR TITLE
Fix error "[qiankun] You need to export lifecycle functions in xxx entry" after page load style error

### PR DESCRIPTION
**Pull request by yangdan8**
…try" after page load style error

##### Checklist

- [x] `npm test` passes
- [ ] tests are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change

- any feature?
- close https://github.com/umijs/qiankun/ISSUE_URL

### CODE REVIEW

**Comment by kuitos** [comment]
Could you please introduce what the pr fix for?

**Comment by yangdan8** [comment]
> Could you please introduce what the pr fix for?

If the loading fails, the next micro-app cannot be loaded

**Comment by kuitos** [comment]
> If the loading fails, the next micro-app cannot be loaded

Can't reproduce with [examples](https://github.com/umijs/qiankun/tree/master/examples), shall we open an issue and provide the reproduction?

**Comment by yangdan8** [comment]
> > If the loading fails, the next micro-app cannot be loaded
> 
> Can't be reproduced with [examples](https://github.com/umijs/qiankun/tree/master/examples), shall we open an issue and provide the reproduction?

After a micro application removes the bootstrap / Mount / unmount function, it loads the micro application, and then it cannot load other micro applications. The same problem also occurs when the network is abnormal

**Comment by yangdan8** [comment]
> Could you please introduce what the pr fix for?

I didn't see the specific reason for Ci's error

**Comment by kuitos** [comment]
closed via can't reproduce

**Pull request closed without merging**
