### PR TITLE
Add new api "unregisterMicroApp"

### PR DESCRIPTION
**Pull request by yangdan8**
update

##### Checklist

- [x] `npm test` passes
- [x] tests are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change

- any feature?
- close https://github.com/umijs/qiankun/ISSUE_URL

### CODE REVIEW

**Comment by kuitos** [comment]
unregisterMicroApp just exposed in devtools, but not for normal users, check the discussion https://github.com/single-spa/single-spa/pull/303#discussion_r280583916

**Comment by yangdan8** [comment]
-----------English-----------
There are some micro-applications in the system that cannot be determined. The user needs to click on the first-level menu and obtain it from the background interface before registering, but different first-level menus need to register different micro-applications. If the previous micro-applications have no anti-registration mechanism, it may cause The same URL under different first-level menus cannot be registered
------------中文-------------
系统有些什么微应用不能确定,需要用户点击一级菜单后从后台接口获取后才注册,但是不同的一级菜单需要注册不同的微应用,如果之前的微应用没有办法反注册机制,那么可能导致不同一级菜单下的相同url无法注册

**Comment by kuitos** [comment]
I think there are tow solutions:
1. open an issue on [single-spa](https://github.com/single-spa/single-spa/issues) and discuss the possibility of exposing `unregisterApplication` api
2. use `loadMicroApp` instead of `registerMicroApps` to control the lifecycle of micro app all by your self

**Comment by kuitos** [comment]
close via https://github.com/single-spa/single-spa/pull/603

**Comment by xiaoLus** [comment]
@kuitos single-spa 已经提供 unregisterApplication 了，qiankun是否会跟进？ https://github.com/single-spa/single-spa/releases/tag/v5.8.0

**Pull request closed without merging**
