### PR TITLE
Get global state

### PR DESCRIPTION
**Pull request by tcper**
##### Checklist

- [x] `npm test` passes
- [x] tests are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change

- As a global message bus, I think `onGlobalStateChange ` is not enough.
- Add convenient get global state data

### CODE REVIEW

**Comment by kuitos** [comment]
@dbkillerf6

**Comment by kuitos** [comment]
IMO you could use `onGlobalStateChange(state => {}, true)` to simulate `getGlobalState`, who combined getter and observer into one ,inspired by rxjs `Subject.subscribe` design philosophy.

**Comment by tcper** [comment]
> IMO `getGlobalState` is not necessary, you could use `onGlobalStateChange(state => {}, true)` to simulate `getGlobalState` instead, who combined getter and observer into one ,inspired by rxjs `Subject.subscribe` design philosophy.

Saw it, I think it's doable,
But it is  redundancy, fold a getter function into a closure.

**Comment by kuitos** [comment]
> But it is redundancy, fold a getter function into a closure.

Not agreed, it is a common design in reactive programming with my knowledge.

**Comment by tcper** [comment]
> > But it is redundancy, fold a getter function into a closure.
> 
> Not agreed, it is a common design in reactive programming with my knowledge.

A simple stage, click button pop up a bubble
```
onClick = () => {
  message.info(getCurrentGlobalState());
}
```
Your way
```
onClick = () => {
  onGlobalStateChange(state => {
    message.info(state);
  }, true);
}
```
I think we need more readable code more than great philosophy.
Without your inform, I didn't even notice this immediate fire thing.

**Comment by kuitos** [comment]
Keep acquisition and subscription are consistent is basic design principle in reactive programming, not such a great philosophy imo, it can help the practice of single source of truth and the abuse of global state.

**Comment by dbkillerf6** [comment]
@kuitos 
I think @tcper  needs an API to get the global status synchronously. In theory, this behavior can be allowed if it is only a read operation.
But even so, I recommend subscribing the global data to the application and then reading the data in the application if your global state contains page rendering data.

**Comment by fengxianqi** [comment]
I think it is nessary to add a `getGlobalState` api.  Sub-app can easily get father's store when mount instead of using onGlobalChange.

**Comment by wibed** [comment]
I too would prefer a synchronous store access method.

**Comment by yuki070** [comment]
Let's see my solutions.

https://github.com/yuki070/qiankun-redux

I use redux to make the global state instead of `initGlobalState`. Of course, this also can be do in qiankun itself.

**Comment by YuhuiRainie** [comment]
I vote for "getGlobalState"

**Comment by kuitos** [comment]
closed via we will not recommend global state api at next major version

**Comment by A-floweR-y** [comment]
> > > But it is redundancy, fold a getter function into a closure.
> > 
> > 
> > Not agreed, it is a common design in reactive programming with my knowledge.
> 
> A simple stage, click button pop up a bubble
> 
> ```
> onClick = () => {
>   message.info(getCurrentGlobalState());
> }
> ```
> 
> Your way
> 
> ```
> onClick = () => {
>   onGlobalStateChange(state => {
>     message.info(state);
>   }, true);
> }
> ```
> 
> I think we need more readable code more than great philosophy. Without your inform, I didn't even notice this immediate fire thing.

@kuitos I think `getGlobalState` sounds better.

The first time I used `qiankun`, I tried to retrieve the state content set by the `initGlobalState` method through `onGlobalStateChange(callback)` but found it not executing. I have been searching for a method like `getGlobalState` or whether `globalState` is globally mounted. I consulted the documentation and used Google search, but did not find the required information until I visited GitHub and discovered that the `onGlobalStateChange` method has a second parameter, which when set to true is similar to `getGlobalState`.

**Pull request closed without merging**
