### PR TITLE
:bug: props should be get and set successfully after sandbox is inactive

### PR DESCRIPTION
**Pull request by luruozhou**
##### Checklist

- [x] `npm test` passes
- [x] tests are included
- [x] commit message follows commit guidelines

##### Description of change

- close https://github.com/umijs/qiankun/issues/863
- close https://github.com/umijs/qiankun/issues/892

### CODE REVIEW

**Comment by kuitos** [comment]
Inactive sandbox indicates that an application is unmounted, and it seems illogical if an unmounted application could set values to global imo.

This may not be the right solution for #863 issue, as we didn't what it happened in fact.

**Comment by luruozhou** [comment]
It is inevitable that in some cases, the global property will be set for the application after unloading. Moreover, the global settings of sub applications are based on sandbox and will not affect the global environment of other applications. Of course, try to avoid this, so console warning can help developers prevent such things. To say the least, even if you can't set the global property after the app is unloaded, you need to be able to get the previously set value after the sub app is unloaded.

**Comment by kuitos** [comment]
> the global settings of sub applications are based on sandbox and will not affect the global environment of other applications.

It wills while in legacy or snapshot sandbox.

**Comment by luruozhou** [comment]
I also encounter a similar problem. When the JS of route loaded asynchronously by application nameA is still downloading, the menu is switched to application nameB. then the window['webpackJsonp_nameA'] of nameA cannot be obtained because of unmounted, then JS will report an error.

**Comment by luruozhou** [comment]
> > the global settings of sub applications are based on sandbox and will not affect the global environment of other applications.
> 
> It wills while in legacy or snapshot sandbox.

Yes, but I fix the code for legacy sandbox to avoid affect global environment. The snapshot keep the original behavior unchanged.

**Comment by kuitos** [comment]
> When the JS of route loaded asynchronously by application nameA is still downloading, the menu is switched to application nameB. then the window['webpackJsonp_nameA'] of nameA cannot be obtained because of unmounted, then JS will report an error.

We may should guarantee that the application must be unmounted until its dynamic assets loaded imo, but not to against the semantic of inactive. 

What are your thoughts? @Deturium @howel52

**Comment by howel52** [comment]
Looking at the [chunk issue](https://github.com/umijs/qiankun/issues/892), I think that when an application is unmount, the sandbox only needs to ensure that the side effects of its activation are isolated.  From my point of this view, it is a bit counterintuitive that the inactive sandbox can still be set value.

**Comment by luruozhou** [comment]
In my opinion,  application unmount is very different from browser refresh, because the resource of application are still there and the asynchronous code such as logic with ajax could still run after application is unmounted.

**Comment by luruozhou** [comment]
Usually we prefer not to run code after the app is inactive,  but some code will run ineluctably  after the app is unmount in some asynchronous scenario, such as code running after js resource loaded or ajax complete

**Comment by kuitos** [comment]
After a small internal discussion, we thought the more reasonable approach is to abort the execution while app had been unmounted, as the execution of dynamic loading scripts are under our control.

**Comment by luruozhou** [comment]
> After a small internal discussion, we thought the more reasonable approach is to abort the execution while app had been unmounted, as the execution of dynamic loading scripts are under our control.

Fine, what I want is just not to see the load chunk error, I'm glad that you have a better way to resolve it.

**Comment by deeWong** [comment]
> After a small internal discussion, we thought the more reasonable approach is to abort the execution while app had been unmounted, as the execution of dynamic loading scripts are under our control.

When will it be updated?

**Pull request closed without merging**
