### PR TITLE
在examples下添加主应用和子应用均为 vue-cli3 的demo

### PR DESCRIPTION
**Pull request by wusp1994**
##### Checklist

- [ ] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

- any feature?
- close https://github.com/umijs/qiankun/ISSUE_URL

### CODE REVIEW

**Comment by kuitos** [comment]
增加一个 vue 子应用就可以了吧？

**Comment by wusp1994** [comment]
@kuitos  嗯，在主应用中配置下端口就可以了

**Comment by kuitos** [comment]
改一下？把其中一个作为子应用提交到 examples 里

**Comment by wusp1994** [comment]
嗯，好了

**Comment by kuitos** [comment]
thx for your contribution!

**Pull request merged**
