### PR TITLE
variable names 'importEntryOpts' is not defined, seems meaningless to…

### PR DESCRIPTION
**Pull request by alison996**

### CODE REVIEW

**Comment by kuitos** [comment]
Could your pls provide a screenshot of this error stack or a reproduction? I have not seen this exception before.

**Comment by alison996** [comment]
> 

Deconstruct a undefined varible not lead to show exception. I just consider it has no meanings, why not remove this varible?

**Comment by alison996** [comment]
image
Deconstruct a undefined varible not lead to show exception. I just consider it has no meanings, why not remove this varible?

**Comment by kuitos** [comment]
importEntryOpts is the reset parameters of `configuration`, not a own field of `configuration`

**Comment by alison996** [comment]
> importEntryOpts is the reset parameters of `configuration`, not a own field of `configuration`

Thank for your explanation🫶

**Pull request closed without merging**
